### ISSUE TITLE
Feature request - API go enable / disable this gem

### ISSUE THREAD

**Issue by PikachuEXE** [igorkasyanchuk/execution_time#1]
Maybe env var and/or class/module methods

Edit: Sorry about empty content, press enter and it submitted o.o

**Comment by igorkasyanchuk** [comment]
What do you mean? Please show sample

**Comment by igorkasyanchuk** [comment]
Or screenshot

**Comment by PikachuEXE** [comment]
Example:
https://github.com/flyerhzm/bullet
```ruby
config.after_initialize do
  Bullet.enable = true
end
```

**Comment by igorkasyanchuk** [comment]
added, in the console you can do now `ExecutionTime.disable!` or `ExecutionTime.enable!`

**Comment by PikachuEXE** [comment]
Good!
Then I can use my own code to enable/disable it whenever I like
